"""Qt-facing bridge between :mod:`anirss.core` and the desktop widgets."""

from __future__ import annotations

import logging
import re
import threading
import time
from collections.abc import Mapping
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from PySide6.QtCore import QObject, QUrl, Signal
from PySide6.QtGui import QDesktopServices

from .core.downloaders import classify_download
from .core.models import (
    AppSettings,
    DownloadKind,
    DownloadStatus,
    DownloadTask,
    ServiceEvent,
    ServiceEventType,
    Subscription,
)
from .core.service import AniRSSService
from .single_instance import SingleInstanceLock

logger = logging.getLogger(__name__)


def _human_bytes(value: float | int) -> str:
    size = float(max(0, value))
    units = ("B", "KB", "MB", "GB", "TB")
    for unit in units:
        if size < 1024 or unit == units[-1]:
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024
    return "0 B"


def _duration_text(seconds: float) -> str:
    seconds = max(0, int(seconds))
    if seconds < 60:
        return f"{seconds} 秒"
    minutes, seconds = divmod(seconds, 60)
    if minutes < 60:
        return f"{minutes} 分 {seconds:02d} 秒"
    hours, minutes = divmod(minutes, 60)
    return f"{hours} 小时 {minutes:02d} 分"


def _unescape_keyword(value: str) -> str:
    """Reverse the simple output produced by :func:`re.escape`."""

    return re.sub(r"\\(.)", r"\1", value)


def _split_escaped_alternatives(value: str) -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    escaped = False
    for character in value:
        if escaped:
            current.extend(("\\", character))
            escaped = False
        elif character == "\\":
            escaped = True
        elif character == "|":
            parts.append("".join(current))
            current.clear()
        else:
            current.append(character)
    if escaped:
        current.append("\\")
    parts.append("".join(current))
    return parts


def _keywords_from_pattern(pattern: str | None, *, require_all: bool) -> list[str]:
    """Recover keyword lists generated by the core, falling back to the regex."""

    if not pattern:
        return []
    if require_all:
        tokens = re.findall(r"\(\?=\.\*((?:\\.|[^)])*)\)", pattern)
        rebuilt = "".join(f"(?=.*{token})" for token in tokens)
        if tokens and rebuilt == pattern:
            return [_unescape_keyword(token) for token in tokens]
    elif pattern.startswith("(?:") and pattern.endswith(")"):
        body = pattern[3:-1]
        tokens = _split_escaped_alternatives(body)
        if tokens:
            return [_unescape_keyword(token) for token in tokens]
    # A subscription imported from an older build may contain a hand-written
    # regex.  Showing it is preferable to silently discarding the rule.
    return [pattern]


class DesktopController(QObject):
    """Expose stable, mapping-based APIs and thread-safe Qt change signals."""

    data_changed = Signal()
    subscriptions_changed = Signal()
    downloads_changed = Signal()
    settings_changed = Signal()
    notification = Signal(str, str)
    error = Signal(str)

    def __init__(
        self,
        service: AniRSSService,
        parent: QObject | None = None,
        *,
        instance_lock: SingleInstanceLock | None = None,
    ) -> None:
        super().__init__(parent)
        self.service = service
        self._instance_lock = instance_lock
        self._closed = False
        self._closing = False
        self._operation_condition = threading.Condition()
        self._active_operations = 0
        self._speed_lock = threading.Lock()
        # task id -> (sample timestamp, bytes, smoothed bytes/second)
        self._speed_samples: dict[int, tuple[float, int, float]] = {}
        self.service.set_event_callback(self._on_service_event)

    # Dashboard -------------------------------------------------------
    def dashboard_snapshot(self) -> dict[str, Any]:
        subscriptions = self.service.list_subscriptions()
        tasks = self.service.list_tasks()
        active = [task for task in tasks if task.status == DownloadStatus.DOWNLOADING]
        completed = sum(task.status == DownloadStatus.COMPLETED for task in tasks)
        with self._speed_lock:
            now = time.monotonic()
            speed = sum(
                sample[2]
                for task_id, sample in self._speed_samples.items()
                if now - sample[0] < 15 and any(task.id == task_id for task in active)
            )
        return {
            "subscription_count": sum(subscription.enabled for subscription in subscriptions),
            "active_downloads": len(active),
            "completed_downloads": completed,
            "download_speed": f"{_human_bytes(speed)}/s" if speed else "0 B/s",
            "next_refresh": self._next_refresh_text(subscriptions),
            "recent_tasks": [self._task_mapping(task) for task in tasks[:8]],
        }

    def _next_refresh_text(self, subscriptions: list[Subscription]) -> str:
        enabled = [subscription for subscription in subscriptions if subscription.enabled]
        if not enabled:
            return "未启用自动刷新"
        settings = self.service.get_settings()
        now = datetime.now(UTC)
        due_times = [
            (subscription.last_checked_at or now)
            + timedelta(
                minutes=subscription.poll_interval_minutes or settings.default_poll_interval_minutes
            )
            for subscription in enabled
        ]
        seconds = (min(due_times) - now).total_seconds()
        return "即将刷新" if seconds <= 1 else f"约 {_duration_text(seconds)}后"

    # Subscriptions ---------------------------------------------------
    def list_subscriptions(self) -> list[dict[str, Any]]:
        folders = {folder.id: folder for folder in self.service.list_subscription_folders()}
        result: list[dict[str, Any]] = []
        for subscription in self.service.list_subscriptions():
            episode_count = (
                self.service.repository.count_feed_items(subscription.id)
                if subscription.id is not None
                else 0
            )
            resolved_save_path = subscription.save_directory or str(
                self.service.subscription_directory(subscription, create=False)
            )
            folder = folders.get(subscription.folder_id)
            result.append(
                {
                    "id": subscription.id,
                    "name": subscription.name,
                    "rss_url": subscription.feed_url,
                    # Keep the editable value empty for automatically derived
                    # show folders.  ``resolved_save_path`` is display-only.
                    "save_path": subscription.save_directory or "",
                    "resolved_save_path": resolved_save_path,
                    "folder_id": subscription.folder_id,
                    "folder_name": folder.name if folder else "",
                    "folder_download_directory": folder.download_directory if folder else "",
                    "include_keywords": _keywords_from_pattern(
                        subscription.include_pattern, require_all=True
                    ),
                    "exclude_keywords": _keywords_from_pattern(
                        subscription.exclude_pattern, require_all=False
                    ),
                    "episode_regex": subscription.episode_pattern or "",
                    "auto_download": subscription.download_enabled,
                    "download_existing": subscription.download_existing,
                    "enabled": subscription.enabled,
                    "last_update": self._datetime_text(subscription.last_checked_at),
                    "episode_count": episode_count,
                }
            )
        return result

    def list_subscription_folders(self) -> list[dict[str, Any]]:
        counts: dict[int, int] = {}
        for subscription in self.service.list_subscriptions():
            if subscription.folder_id is not None:
                counts[subscription.folder_id] = counts.get(subscription.folder_id, 0) + 1
        return [
            {
                "id": folder.id,
                "name": folder.name,
                "download_directory": folder.download_directory,
                "subscription_count": counts.get(folder.id or -1, 0),
            }
            for folder in self.service.list_subscription_folders()
        ]

    def save_subscription_folder(self, data: Mapping[str, Any]) -> dict[str, Any]:
        saved = self.service.save_subscription_folder(data)
        return next(item for item in self.list_subscription_folders() if item.get("id") == saved.id)

    def delete_subscription_folder(self, folder_id: Any) -> bool:
        return self.service.delete_subscription_folder(int(folder_id))

    def move_subscription(self, subscription_id: Any, folder_id: Any | None) -> dict[str, Any]:
        numeric_folder_id = None
        if folder_id is not None and folder_id != "":
            numeric_folder_id = int(folder_id)
        saved = self.service.move_subscription(int(subscription_id), numeric_folder_id)
        return next(item for item in self.list_subscriptions() if item.get("id") == saved.id)

    def save_subscription(self, data: Mapping[str, Any]) -> dict[str, Any]:
        saved = self.service.save_subscription(data)
        return next(item for item in self.list_subscriptions() if item.get("id") == saved.id)

    def delete_subscription(self, subscription_id: Any) -> bool:
        return self.service.delete_subscription(int(subscription_id))

    def refresh_all(self) -> list[DownloadTask]:
        """Refresh synchronously; MainWindow runs this method in a worker."""

        with self._operation_condition:
            if self._closing:
                return []
            self._active_operations += 1
        try:
            return self.service.refresh_all()
        finally:
            with self._operation_condition:
                self._active_operations -= 1
                self._operation_condition.notify_all()

    def refresh_subscription(self, subscription_id: Any) -> list[DownloadTask]:
        """Refresh one subscription; detail dialogs run this in a worker."""

        with self._operation_condition:
            if self._closing:
                return []
            self._active_operations += 1
        try:
            return self.service.refresh_subscription(int(subscription_id))
        finally:
            with self._operation_condition:
                self._active_operations -= 1
                self._operation_condition.notify_all()

    def list_subscription_items(
        self,
        subscription_id: Any,
        limit: int = 300,
    ) -> list[dict[str, Any]]:
        numeric_id = int(subscription_id)
        subscription = self.service.repository.get_subscription(numeric_id)
        if subscription is None:
            raise KeyError(f"subscription {numeric_id} does not exist")
        include = (
            re.compile(subscription.include_pattern, re.I) if subscription.include_pattern else None
        )
        exclude = (
            re.compile(subscription.exclude_pattern, re.I) if subscription.exclude_pattern else None
        )
        tasks = {
            task.feed_item_id: task for task in self.service.list_tasks(subscription_id=numeric_id)
        }
        result: list[dict[str, Any]] = []
        for item in self.service.list_feed_items(numeric_id, limit=max(1, limit)):
            task = tasks.get(item.id or -1)
            matches_rules = not (
                (include is not None and include.search(item.title) is None)
                or (exclude is not None and exclude.search(item.title) is not None)
            )
            kind = (
                classify_download(item.download_url, item.content_type).value
                if item.download_url
                else None
            )
            result.append(
                {
                    "id": item.id,
                    "title": item.title,
                    "episode": item.episode or "",
                    "published_at": self._datetime_text(item.published_at or item.created_at),
                    "description": item.description or "",
                    "link": item.link or "",
                    "download_url": item.download_url or "",
                    "content_type": item.content_type or "",
                    "download_kind": kind,
                    "matches_rules": matches_rules,
                    "task_id": task.id if task else None,
                    "task_status": task.status.value if task else None,
                    "task_error": task.error if task else None,
                }
            )
        return result

    def download_feed_item(self, subscription_id: Any, item_id: Any) -> dict[str, Any]:
        with self._operation_condition:
            if self._closing:
                raise RuntimeError("AniRSS is closing")
            self._active_operations += 1
        try:
            task = self.service.download_feed_item(int(subscription_id), int(item_id))
            return self._task_mapping(task)
        finally:
            with self._operation_condition:
                self._active_operations -= 1
                self._operation_condition.notify_all()

    # Downloads -------------------------------------------------------
    def list_downloads(self, status_filter: str | None = None) -> list[dict[str, Any]]:
        statuses = [status_filter] if status_filter else None
        return [self._task_mapping(task) for task in self.service.list_tasks(statuses)]

    def _task_mapping(self, task: DownloadTask) -> dict[str, Any]:
        subscription = self.service.repository.get_subscription(task.subscription_id)
        item = self.service.repository.get_feed_item(task.feed_item_id)
        with self._speed_lock:
            speed = self._speed_samples.get(task.id or -1, (0.0, 0, 0.0))[2]
        eta = "—"
        if task.status == DownloadStatus.COMPLETED:
            eta = "已完成"
        elif task.status == DownloadStatus.PAUSED:
            eta = "已暂停"
        elif task.status == DownloadStatus.QUEUED:
            eta = "等待中"
        elif task.status == DownloadStatus.FAILED:
            eta = task.error or "下载失败"
        elif (
            task.status == DownloadStatus.DOWNLOADING
            and task.kind == DownloadKind.MAGNET
            and task.total_bytes is None
        ):
            eta = "正在获取磁力元数据"
        elif (
            task.status == DownloadStatus.DOWNLOADING
            and task.kind in {DownloadKind.MAGNET, DownloadKind.TORRENT}
            and speed <= 0
        ):
            eta = "等待可用节点"
        elif speed > 0 and task.total_bytes:
            eta = _duration_text((task.total_bytes - task.downloaded_bytes) / speed)
        return {
            "id": task.id,
            "title": task.title,
            "anime": subscription.name if subscription else "",
            "episode": item.episode if item else None,
            "status": task.status.value,
            "progress": task.progress,
            "speed": f"{_human_bytes(speed)}/s" if speed else "—",
            "size": task.total_bytes,
            "eta": eta,
            "path": task.destination_directory,
            "error": task.error,
            "kind": task.kind.value,
        }

    def pause_download(self, download_id: Any) -> DownloadTask:
        return self.service.pause_task(int(download_id))

    def resume_download(self, download_id: Any) -> DownloadTask:
        return self.service.resume_task(int(download_id))

    def remove_download(self, download_id: Any, delete_files: bool = False) -> bool:
        with self._operation_condition:
            if self._closing:
                return False
            self._active_operations += 1
        try:
            return self.service.remove_task(int(download_id), delete_files=delete_files)
        finally:
            with self._operation_condition:
                self._active_operations -= 1
                self._operation_condition.notify_all()

    # Settings --------------------------------------------------------
    def load_settings(self) -> dict[str, Any]:
        return self._settings_mapping(self.service.get_settings())

    def save_settings(self, values: Mapping[str, Any]) -> dict[str, Any]:
        aliases = {
            "download_directory": "download_root",
            "poll_interval_minutes": "default_poll_interval_minutes",
            "proxy": "proxy_url",
            "start_on_boot": "autostart",
            "notifications": "notifications_enabled",
            "seed_after_complete": "seed_after_completion",
            "seed_minutes": "seed_time_minutes",
        }
        converted: dict[str, Any] = {}
        for key, value in values.items():
            converted[aliases.get(key, key)] = value
        saved = self.service.save_settings(converted)
        return self._settings_mapping(saved)

    @staticmethod
    def _settings_mapping(settings: AppSettings) -> dict[str, Any]:
        return {
            "download_directory": settings.download_root,
            "max_concurrent_downloads": settings.max_concurrent_downloads,
            "poll_interval_minutes": settings.default_poll_interval_minutes,
            "proxy": settings.proxy_url or "",
            "start_on_boot": settings.autostart,
            "minimize_to_tray": settings.minimize_to_tray,
            "notifications": settings.notifications_enabled,
            "seed_after_complete": settings.seed_after_completion,
            "seed_minutes": settings.seed_time_minutes,
            "listen_port": settings.listen_port,
            "bt_metadata_timeout_seconds": settings.bt_metadata_timeout_seconds,
            "bt_stall_timeout_seconds": settings.bt_stall_timeout_seconds,
            "theme": settings.theme,
        }

    def open_folder(self, path: str) -> bool:
        directory = Path(path).expanduser()
        if not directory.exists():
            raise FileNotFoundError(f"目录不存在：{directory}")
        return QDesktopServices.openUrl(QUrl.fromLocalFile(str(directory.resolve())))

    # Lifecycle/events ------------------------------------------------
    def start(self) -> None:
        self.service.start()

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        with self._operation_condition:
            self._closing = True
        self.service.set_event_callback(None)
        try:
            # stop() sets a cooperative refresh cancellation flag.  A feed
            # request already inside urllib may take up to its configured
            # timeout, so wait for the UI worker before closing SQLite.
            self.service.stop()
        except Exception:
            logger.exception("AniRSS did not shut down cleanly")
            return
        deadline = time.monotonic() + self.service.get_settings().request_timeout_seconds + 5
        with self._operation_condition:
            while self._active_operations and time.monotonic() < deadline:
                self._operation_condition.wait(max(0.0, deadline - time.monotonic()))
            if self._active_operations:
                logger.error("A background UI operation did not stop in time; keeping SQLite open")
                return
        try:
            self.service.close()
        except Exception:
            logger.exception("AniRSS did not close its database cleanly")
        else:
            if self._instance_lock is not None:
                self._instance_lock.release()

    def _on_service_event(self, event: ServiceEvent) -> None:
        if event.type == ServiceEventType.TASK_UPDATED and event.task_id is not None:
            self._record_speed(event.task_id, event.payload)
            self.downloads_changed.emit()
            self.data_changed.emit()
            if event.payload.get("status") == DownloadStatus.COMPLETED.value:
                task = self.service.get_task(event.task_id)
                self.notification.emit("下载完成", task.title if task else "任务已完成")
        elif event.type == ServiceEventType.TASK_ADDED:
            self.downloads_changed.emit()
            self.data_changed.emit()
            task = self.service.get_task(event.task_id) if event.task_id is not None else None
            title = "已加入下载" if event.payload.get("manual") else "发现新剧集"
            self.notification.emit(title, task.title if task else "新任务已加入队列")
        elif event.type == ServiceEventType.TASK_REMOVED:
            self.downloads_changed.emit()
            self.data_changed.emit()
        elif event.type in {
            ServiceEventType.SUBSCRIPTION_SAVED,
            ServiceEventType.SUBSCRIPTION_DELETED,
            ServiceEventType.SUBSCRIPTION_FOLDER_SAVED,
            ServiceEventType.SUBSCRIPTION_FOLDER_DELETED,
        }:
            self.subscriptions_changed.emit()
            self.data_changed.emit()
        elif event.type == ServiceEventType.SETTINGS_SAVED:
            self.settings_changed.emit()
            self.data_changed.emit()
        elif event.type == ServiceEventType.REFRESH_FINISHED:
            self.subscriptions_changed.emit()
            self.downloads_changed.emit()
            self.data_changed.emit()
        elif event.type in {ServiceEventType.REFRESH_FAILED, ServiceEventType.ERROR}:
            self.error.emit(event.message or "后台任务失败")

    def _record_speed(self, task_id: int, payload: Mapping[str, Any]) -> None:
        downloaded = int(payload.get("downloaded_bytes") or 0)
        now = time.monotonic()
        with self._speed_lock:
            previous = self._speed_samples.get(task_id)
            speed = 0.0
            if previous and now > previous[0] and downloaded >= previous[1]:
                instant = (downloaded - previous[1]) / (now - previous[0])
                speed = instant if previous[2] <= 0 else previous[2] * 0.65 + instant * 0.35
            self._speed_samples[task_id] = (now, downloaded, speed)

    @staticmethod
    def _datetime_text(value: datetime | None) -> str:
        if value is None:
            return "尚未刷新"
        local = value.astimezone()
        now = datetime.now().astimezone()
        if local.date() == now.date():
            return f"今天 {local:%H:%M}"
        if local.date() == (now - timedelta(days=1)).date():
            return f"昨天 {local:%H:%M}"
        return local.strftime("%Y-%m-%d %H:%M")


__all__ = ["DesktopController"]
